// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm2VuF6_YmmXlmL7ZSDvmjyrEfCkQ7WPQ',
    appId: '1:989595330356:web:a097030fcc731e9a8f2761',
    messagingSenderId: '989595330356',
    projectId: 'melody-projet',
    authDomain: 'melody-projet.firebaseapp.com',
    storageBucket: 'melody-projet.firebasestorage.app',
    measurementId: 'G-SGX62KYHGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAANnl6z0sw8Gb2QWOma3Mc-IjENRaUeqg',
    appId: '1:989595330356:android:891a44b700a621d38f2761',
    messagingSenderId: '989595330356',
    projectId: 'melody-projet',
    storageBucket: 'melody-projet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3vGMl0lx7chRBjiPZxqfKV2wcOEhfVLw',
    appId: '1:989595330356:ios:4a85ae333cf8e8e58f2761',
    messagingSenderId: '989595330356',
    projectId: 'melody-projet',
    storageBucket: 'melody-projet.firebasestorage.app',
    iosBundleId: 'com.melody.app.melody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3vGMl0lx7chRBjiPZxqfKV2wcOEhfVLw',
    appId: '1:989595330356:ios:4a85ae333cf8e8e58f2761',
    messagingSenderId: '989595330356',
    projectId: 'melody-projet',
    storageBucket: 'melody-projet.firebasestorage.app',
    iosBundleId: 'com.melody.app.melody',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm2VuF6_YmmXlmL7ZSDvmjyrEfCkQ7WPQ',
    appId: '1:989595330356:web:e90e8cd74ff641948f2761',
    messagingSenderId: '989595330356',
    projectId: 'melody-projet',
    authDomain: 'melody-projet.firebaseapp.com',
    storageBucket: 'melody-projet.firebasestorage.app',
    measurementId: 'G-7J6LV0ZNP9',
  );
}
